name: PIMS Setup

on:
  repository_dispatch:
    types: [setup-pims]
  workflow_dispatch:
    inputs:
      setup_labels:
        description: 'Setup PIMS labels'
        required: true
        default: true
        type: boolean
      setup_actions:
        description: 'Setup PIMS GitHub Actions'
        required: true
        default: true
        type: boolean

jobs:
  setup-labels:
    if: ${{ github.event.inputs.setup_labels != false }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Labels
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const fs = require('fs');
            const yaml = require('js-yaml');
            
            // Install js-yaml if not available
            if (!yaml.load) {
              const { execSync } = require('child_process');
              execSync('npm install js-yaml', { stdio: 'inherit' });
              delete require.cache[require.resolve('js-yaml')];
              const yamlNew = require('js-yaml');
              Object.assign(yaml, yamlNew);
            }
            
            try {
              const labelsFile = fs.readFileSync('.github/labels.yml', 'utf8');
              const labels = yaml.load(labelsFile);
              
              for (const label of labels) {
                try {
                  await github.rest.issues.createLabel({
                    owner: context.repo.owner,
                    repo: context.repo.repo,
                    name: label.name,
                    color: label.color,
                    description: label.description
                  });
                  console.log(`Created label: ${label.name}`);
                } catch (error) {
                  if (error.status === 422) {
                    // Label already exists, update it
                    await github.rest.issues.updateLabel({
                      owner: context.repo.owner,
                      repo: context.repo.repo,
                      name: label.name,
                      color: label.color,
                      description: label.description
                    });
                    console.log(`Updated label: ${label.name}`);
                  } else {
                    console.error(`Error with label ${label.name}:`, error);
                  }
                }
              }
            } catch (error) {
              console.error('Error processing labels file:', error);
              core.setFailed(error.message);
            }

  setup-actions:
    if: ${{ github.event.inputs.setup_actions != false }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup PIMS Actions
        run: |
          echo "PIMS GitHub Actions setup completed"
          echo "Available workflows:"
          echo "- pims-setup.yml: Initial PIMS setup"
          echo "- pims-ci.yml: Continuous integration"
          echo "- pims-knowledge.yml: Knowledge accumulation automation"
          
          # Create .cursor/rules directory if it doesn't exist
          mkdir -p .cursor/rules
          
          # Create initial knowledge.mdc if it doesn't exist
          if [ ! -f ".cursor/rules/knowledge.mdc" ]; then
            cat > .cursor/rules/knowledge.mdc << 'EOF'
# PIMS知識蓄積ファイル

## 更新履歴
- $(date): PIMS初期化

## 成功パターン

## 失敗パターン

## 再発防止ルール
EOF
            echo "✅ Created initial knowledge.mdc file"
          else
            echo "ℹ️ knowledge.mdc already exists"
          fi
